# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{content_blocks}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pawe\305\202 Pacana"]
  s.date = %q{2010-12-20}
  s.description = %q{Content blocks are commonly used models representing editable page partials.}
  s.email = %q{pawel.pacana@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "content_blocks.gemspec",
    "lib/content_blocks.rb",
    "lib/content_blocks/snippet.rb",
    "lib/generators/content_blocks/snippet_generator.rb",
    "lib/generators/content_blocks/templates/migration.rb",
    "spec/schema/schema.rb",
    "spec/snippet_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/pawelpacana/content_blocks}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Content parts models for your site.}
  s.test_files = [
    "spec/schema/schema.rb",
    "spec/snippet_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_runtime_dependency(%q<aasm>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 2.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<aasm>, ["~> 2.2.0"])
      s.add_runtime_dependency(%q<RedCloth>, ["~> 4.2.3"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0"])
      s.add_development_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.1.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<aasm>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, ["~> 2.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<aasm>, ["~> 2.2.0"])
      s.add_dependency(%q<RedCloth>, ["~> 4.2.3"])
      s.add_dependency(%q<activerecord>, [">= 3.0"])
      s.add_dependency(%q<rspec>, [">= 2.1.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.1.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, ["~> 3.0.3"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<aasm>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, ["~> 2.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<aasm>, ["~> 2.2.0"])
    s.add_dependency(%q<RedCloth>, ["~> 4.2.3"])
    s.add_dependency(%q<activerecord>, [">= 3.0"])
    s.add_dependency(%q<rspec>, [">= 2.1.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.1.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
  end
end

